<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/7/11
 * Time: 15:42
 */
namespace app\api\controller;
use think\facade\Db;
use think\Request;
class MemberController extends Api {
    public function initialize(){
//        parent::initialize(); // TODO: Change the autogenerated stub
//        self::$param = input();
//        $token = self::$param ['token'];
        //查询当前用户id
//        $uid = Db::name('user_token') -> where('token',$token) -> value('user_id');
        $uid = 17;
        $this -> topup_check($uid);
    }
    //检测是否到期
    public function topup_check($uid){
        //查询充值表
        $topupcheck= Db::name('topup') -> where('uid',$uid) -> find();
        if(!empty($topupcheck)){
            if(time() - strtotime($topupcheck['end_time']) > 0){
                exit(echoMsg('fail','401','对不起，你卡内余额不足，如需使用，请充值',''));
            }
        }
    }
}