<?php
//    / **
//    *由PhpStorm创建。
//    *用户：管理员
//    *日期：2020/8/22
//    *时间：12:48
//    * /
namespace app\api\controller;
use DsfApi\PddApi;
use think\facade\Db;
use app\Request;
//use think\Request;
use think\facade\Session;
use think\facade\Cache;
use fast\Image;
use fast\Redis;
use DsfApi\TaoBao;

class Pnduoduo extends Api {
    protected  $accessToken;
    protected  $pddarray;
    public  function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $pddauth = Db::name('business_application_platform') -> where('name','pdd')  -> field('appkey,appsecret,redirect_uri') -> find();
        $config = array(
            'client_id' =>$pddauth['appkey'], //client_id
            'client_secret' => $pddauth['appsecret'], //client_secret
            'backurl' => $pddauth['redirect_uri'], //回调地址
            'data_type' => 'json', // 返回数据格式
            'pdd_token_file' => __DIR__ . '/pdd_token.txt', // token存储文件地址
        );
        $this -> pddarray = new PddApi($config);
        $owner_name = input('owner_name');
//         if(empty($owner_name)){
//             exit(json_encode($this -> error('401','店铺账号不能为空!'))) ;
//         }

        $res = Db::name('shop_open_user')
            -> field('mall_name,access_token,refresh_token,endtime,owner_name,owner_id,is_token')
            -> where(['shop_type'=>'pdd','owner_name'=>$owner_name])
            -> find();
//        if($res['is_token'] != 1){
//            exit(json_encode($this -> error('403','此店铺没有授权!'))) ;
//        }

//        if(time() - $res['endtime'] > 2*60*60){
//            exit(json_encode($this -> error('403','此店铺授权过期，请重新授权!'))) ;
//        }
        Db::name('shop_open_user')
            -> where(['shop_type'=>'pdd','owner_name'=>$owner_name])
            -> update(['endtime'=>time()]);
         $this -> accessToken = $res['access_token'];
    }

    //获取店铺信息
    public function getShopInfo(Request $request){

    }


    //导入拼多多图片信息
    public function pdduploadpic(Request $request){
        set_time_limit(0);
        $type = $request->post('type');
        $goodsid = $request->post('goodid');
        if(empty($goodsid)){
            return $this -> error('401','商品ID不能为空!');
        }
//        $goodsid = "629385298883";
        $res = TaoBao::goodsinfo($goodsid);
        Cache::set($type.$goodsid,$res);
        //商品标题
        Redis::set($this->uid.$goodsid. '_title',$res['title'], 604800);
        //商品主图
        $str = substr($res['pic_url'],-3);
        $ztimgurl = '';
        if($str == 'jpg' || $str == 'png'){
            $ztimgurl = $this -> imgupload($res['pic_url'],1,700,700);
        }
        Redis::set($this->uid.$goodsid . '_product_ztimg', serialize($ztimgurl), 604800);
        $product_images_url = Redis::get($goodsid . '_product_images_url');
        if($product_images_url){
            $pddlunbo = [];//轮播图
            $images = $res['item_imgs'];
            if(count($images) > 15){
                $imgeq =  array_slice($images,0,15);
            }else{
                $imgeq = $images;
            }
            foreach ($imgeq as $v){
                $str = substr($v,-3);
                if($str == 'jpg' || $str == 'png'){
                    $esimg = $this -> imgupload($v,1,700,700);
                    if($esimg){
                        $pddlunbo[]   = $esimg;
                    }
                }
            }
            Redis::set($goodsid . '_product_images_url', serialize($pddlunbo), 604800);
        }

//        Redis::Del($goodsid .'_product_descImg');
        $descImg = Redis::get($goodsid . '_product_descImg');
        if($descImg){
            $desc_img = []; //详情图
            $desc_img1 = $res['desc_img'];
            if(count($res['desc_img']) >= 30){
                $desc_img2 =  array_slice($res['desc_img'],0,30);
            }else if(count($res['desc_img']) == 0){
                $desc_img2 = $res['item_imgs'];
            }else{
                $desc_img2 = $res['desc_img'];
            }
            foreach ($desc_img2 as $v){
                $esimg1 = $this -> imgupload($v,1,700,700);
                if($esimg){
                    $desc_img[]   = $esimg1;
                }
//                $desc_img[] = $this -> imgupload($v,1,700,700);
            }
//            foreach ($desc_img as $k => $v){
//                if($v == null){
//                    unset($desc_img[$k]);
//                }
//            }
//            $desc_img1 = array_merge($desc_img);
            Redis::set($goodsid . '_product_descImg', serialize($desc_img1), 604800);
        }
        $data['pic_url'] = unserialize(Redis::get($this->uid.$goodsid . '_product_ztimg'));
        $data['msg'] = "上传图片成功";
        // $data['images_url'] = unserialize(Redis::get($goodsid . '_product_images_url'));
//         $data['desc_img'] = unserialize(Redis::get($goodsid . '_product_descImg'));
        $data['goodsid'] = $goodsid;
        return $this->success('200','获取成功', $data);
    }

    public function Ansypddupload(Request $request){
        header("content-type:text/html;charset=utf-8");
        $param = $request->param();
    }
    //导入上传
    public function pdduploadinfo(Request $request){
        $type = $request->post('type');
        $goodsid = $request->post('goodid') ;
        $filerprice = $request->post('filerprice')  ;//团购价
        $filergeprice = $request->post('filergeprice') ;//单卖价
        if (empty($goodsid)) {
            return $this->error('401', '商品ID不能为空!');
        }
        $res = Cache::get($type . $goodsid);
//        dump(count( $res['skus_list']));die;
        switch ($type) {
            case 'taobao':
                $rescate = TaoBao::goodcate($goodsid);
                break;
        }
        //查询类目
        $str = '';
        if(mb_strlen($rescate['cat_name']) > 2){
            $str .= mb_substr($rescate['cat_name'], -2,2,'utf-8');
        }else{
            $str .= $rescate['cat_name'];
        }
        $wherecname = [
            ['cat_name', 'like', "%".$str."%"],
        ];

        $cat_id = Db::name('pdd_goods_cat') -> where('level = 3 or level =4')->where($wherecname)-> value('cat_id');
        if (!empty($cat_id)) {
            //商品sku列表
            if(count($res['skus_list']) >= 20) {
                $skus_list = array_slice($res['skus_list'], 0, 20);
            }else{
                $skus_list = $res['skus_list'];
            }

            if(count($res['prop_imgs']) >= 20) {
                $prop_imgs = array_slice($res['prop_imgs'], 0, 20);
            }else{
                $prop_imgs = $res['prop_imgs'];
            }
            $sku_list = $this->skus_list($cat_id,$skus_list, $prop_imgs,$filerprice,$filergeprice);
            Redis::set($this->uid.$goodsid . '_sku_list', serialize($sku_list), 604800);
            //商品属性
            if(count($res['props']) >=20){
                $props = array_slice($res['props'], 0, 20);
            }else{
                $props = $res['props'];
            }
            $goods_properties = $this->getAttrcats($cat_id, $props, $res['pic_url']);
            Redis::set($this->uid.$goodsid . '_attr', serialize($goods_properties), 604800);
            $data['cat_id'] =   $this->getcat_id($wherecname);
            $data['desc_short'] = $res['desc_short'];//商品简介
            $data['out_goods_id'] = "WPK-T-" . $res['goodsid']; //商品外部编码
//            $data['carousel_video'] = json_encode([]);
            Redis::set($this->uid.$goodsid . '_info', serialize($data), 604800);
        }
        $sudata['msg'] = "上传详情成功";
        $sudata['goodsid'] = $goodsid;
        return $this->success('200', '上传图片成功', $sudata);
    }
    //开始上传
    public function pddgoodsadd(Request $request){
        $template_id = $request->post('template_id') ?? '147120650715681';
        $goods_type = $request->post('goods_type') ?? 1; //1-国内普通商品，2-进口
        $goodsid = $request->post('goodid') ?? '567892068402';
        $type = $request->post('type');
        if(empty($template_id)){
            return $this -> error('401','运费模板不能为空!');
        }
        if(empty($goodsid)){
            return $this -> error('401','商品ID不能为空!');
        }
        $skulist = unserialize(Redis::get($this->uid.$goodsid.'_sku_list'));
        $last_names = array_column($skulist,'price');
        array_multisort($last_names,SORT_DESC,$skulist);
        $pddsku = unserialize(Redis::get($this->uid.$goodsid.'_info'));
//        dump(unserialize(Redis::get($goodsid.'_info')));die;
        $pdd_data = [
            'bad_fruit_claim'=>'',
            'buy_limit'=>'',//限购次数   非必填
            'carousel_video' => '[]',
            'carousel_video_url'=>'',
            'cat_id'=> $pddsku['cat_id'], //叶子类目ID
            'cost_template_id' => $template_id, //物流运费模板ID，可使用pdd.logistics.template.get获取
            'country_id' => 0,//国家ID，country_id可以通过pdd.goods.country.get获取
            'customer_num' => '',//团购人数    非必填
            'customs' => '',//非必填
            'delivery_one_day' => 0,//	是否当日发货,0 否，1 是  非必填
            'carousel_gallery'=> json_encode(unserialize(Redis::get($goodsid.'_product_images_url'))), //商品轮播图
            'detail_gallery'=> json_encode(unserialize(Redis::get($goodsid.'_product_descImg'))),//商品详情图
            'elec_goods_attributes'=>'',
            'goods_name'=> Redis::get($this->uid.$goodsid. '_title') ,//	商品标题
            'goods_desc' => $pddsku['desc_short'],//商品描述
            'goods_properties'=> json_encode(unserialize(Redis::get($goodsid.'_attr'))),//	商品属性列表  非必填
            'goods_trade_attr' => '',//日历商品交易相关信息   非必填
            'goods_travel_attr'=> '',//商品出行信息  非必填
            'goods_type' => $goods_type,//1-国内普通商品，2-进口
            'image_url'=> unserialize(Redis::get($this->uid.$goodsid.'_product_ztimg')),//	商品主图
            'invoice_status' => 0,//是否支持开票（测试中）
            'is_customs' => 'false',//是否需要上报海关，false-无需上报海关，true-需上报海关  非必填
            'is_folt' => 'true',//是否支持假一赔十，false-不支持，true-支持
            'is_pre_sale' => 'false',//是否预售,true-预售商品，false-非预售商品
            'is_refundable' => 'true',//是否7天无理由退换货，true-支持，false-不支持
            'second_hand' => 'false',//是否二手商品，true -二手商品 ，false-全新商品
            'lack_of_weight_claim'=>0 ,//缺重包退  非必填
            'mai_jia_zi_ti' => '',
            'market_price' => $skulist[0]['price'] + 1000,//市场价格，单位为分
            'order_limit' => 999999,//单次限量   非必填
            'origin_country_id' => '',//原产地id  非必填
            'out_goods_id' => $pddsku['out_goods_id'],//商品编码
            'oversea_goods'=>'', //非必填
            'oversea_type' => 0,//非必填
            'pre_sale_time' => 0,//预售时间，is_pre_sale为true时必传   非必填
            'quan_guo_lian_bao' => 0,//0：不支持全国联保；1：支持全国联保
            'shang_men_an_zhuang' => '',//上门安装模版id  非必填
            'shipment_limit_second' => 48*3600,
            'size_spec_id' => '',//尺码表id  非必填
            'sku_list' => json_encode(unserialize(Redis::get($this->uid.$goodsid.'_sku_list'))),
            'sku_type' => 0,//	库存方式（0：普通型，1：日历型）
            'song_huo_an_zhuang' => '',//送货入户并安装模版id  非必填
            'song_huo_ru_hu' => '',//送货入户模版id  非必填
            'tiny_name' => '',//短标题，示例：新包装   非必填
            'warehouse' => '',//非必填
            'warm_tips' => '',//买家自提模版id
            'zhi_huan_bu_xiu' => 0,//只换不修的天数，目前只支持0和365  非必填
        ];
        $result  = app('pddapi')->request('pdd.goods.add',$this -> accessToken,$pdd_data);
        if($result['error_response']){
            $data['msg'] = $result['error_response']['error_msg'];
        }else{
            Redis::set("WPK-T-".$goodsid,''.$goodsid,604800);
            $data['msg'] = '上传成功';
//            $this -> goodsrelation($result['goods_add_response']['goods_id'],$type,$goodsid);
        }
        $data['goodsid']  = $goodsid;
        return $this->success('200','上传成功', $data);
    }

    //商品关联信息设置接口
    public function goodsrelation($goods_id,$type,$goodsid){
        $res = Cache::get($type . $goodsid);
        $last_names = array_column($res['skus_list'],'price');
        array_multisort($last_names,SORT_DESC,$res['skus_list']);
        $startp = count($res['skus_list'])-1;
        $data = [
            'goods_id' => $goods_id,//拼多多商品id
            'out_detail_url' => $res['detail_url'],//外部平台商品url
            'out_goods_id' => $goodsid,//外部平台商品id
            'out_high_goods_price' => $res['skus_list'][0]['price'],//外部平台商品最高价，单位：分
            'out_low_goods_price' => $res['skus_list'][$startp]['price'],//外部平台商品最低价，单位：分
            'out_mall_id' =>'',//外部平台店铺id
            'postage' => '',//邮费
            'source_type' => $this -> source_type($type)//外部平台
        ];
//        pdd.goods.relation.set
    }



    /*上传图片
    * $type 类型 1压缩尺寸 0 不压缩
    */
    public function imgupload($images,$type="",$iwidth="",$iheight=""){
        if(empty($images)){
            return false;
        }
        if(strpos($images,'https:') !== false){
            $imageurl = Image::imgtobase64($images,$type,$iwidth,$iheight);
        }elseif(strpos($images,'http:') !== false){
            $imageurl = Image::imgtobase64($images,$type,$iwidth,$iheight);
        }else{
            $imageurl = Image::imgtobase64("http:".$images,$type,$iwidth,$iheight);
        }
        $result  = app('pddapi')->request('pdd.goods.image.upload',$this -> accessToken,[ 'image'=>$imageurl]);
        $imgurl = $result['goods_image_upload_response']['image_url'];
        return  $imgurl;
    }


    /*  获取商品的sku
         *  $pdd_catid 商品类目id
         *   $resskulist  sku 数据
         *   $thumb_urls 缩略图
         * */
    protected function skus_list($pdd_catid,$resskulist,$thumb_urls,$filerprice,$filergeprice){
        $oversea_sku = [
            "measurement_code" => '001',//计量单位编码，从接口pdd.gooods.sku.measurement.list获取code
            "specifications" => "2",//规格
            "taxation" => 100,//税费
        ];
        $thumburl = [];
        foreach ($thumb_urls as $k => $v) {
            $thumburl[$v['properties']] = $v['url'];
        }
        $sku_list = [];
        foreach ($resskulist as $key => $val){
            $propImg = explode(';', $val['properties_name']);
            $ysstr = '';
            $a = '';
            $b = '';
            $cmstr = '';
            $c = '';
            $ccstr = '';
            foreach ($propImg as $v) {
                if ( strpos($v, '颜色')) {
                    $a = strpos($v, '颜色');
                    $ysstr = $v;
                }
                if(strpos($v, '尺码')){
                    $b = strpos($v, '尺码');
                    $cmstr = $v;
                }
                if(strpos($v, '尺寸')){
                    $c = strpos($v, '尺寸');
                    $ccstr = $v;
                }
            }
            $ye = substr($ysstr, $a, strlen($ysstr));
            $cm = substr($cmstr, $b, strlen($cmstr));
            $cc = substr($cmstr, $c, strlen($ccstr));
            $propImgNum = substr($ysstr, 0, $a - 1);
            $sku_list[$key]['is_onsale'] = 1;
            $sku_list[$key]['limit_quantity'] = 999;
            $sku_list[$key]['weight'] = 1000;
            $multi_price = $val['price'] * 100 * floatval($filerprice);
            $sku_list[$key]['multi_price'] = $multi_price;
            $sku_list[$key]['price'] =  $multi_price + floatval($filergeprice) * 100;//($val['price'] + $filergeprice) * 100
            $sku_list[$key]['thumb_url'] = $this -> imgupload($thumburl[$propImgNum]);
            $sku_list[$key]['out_sku_sn'] = time().',';//商品sku外部编码
            $sku_list[$key]['spec_id_list'] = $this ->skupc_list($pdd_catid,$ye,$cm,$cc,'','');
            $sku_list[$key]['quantity'] = $val['quantity'];
            $sku_list[$key]['oversea_sku'] = $oversea_sku;
            $sku_list[$key]['length'] = '';
        }
        //        过滤sku为空的spec_id_list、thumb_url字段
        foreach ($sku_list as $key => $val){
            if($val['spec_id_list'] == '[]' || $val['thumb_url'] == ''){
                unset($sku_list[$key]);
            }
        }
        $sku_list1 = array_merge($sku_list);
        return $sku_list1;
    }
    //商品规格值ID
    protected function skupc_list($cat_id,$ye ="",$cm="",$cc='',$rs='',$r1=''){
        $yearr = explode(':',$ye);
        $cmarr = explode(':',$cm);
        $ccarr = explode(':',$cc);
        $yestr = '';
        if(strpos($yearr[1],'预售') !== false){
            $yestr .= mb_substr($yearr[1], 0,2,'utf-8');
        }else{
            $yestr .= $yearr[1];
        }
        $yespecid = $this -> getpddskuSpecs($cat_id,substr($yearr[0],0,6),$yestr);
        $cmspecid = $this -> getpddskuSpecs($cat_id,$cmarr[0],$cmarr[1]);
        $ccspecid = $this -> getpddskuSpecs($cat_id,$ccarr[0],$ccarr[1]);
        $str = [];
        if($yespecid){
            $str[] = $yespecid;
        }
        if($cmspecid){
            $str[] = $cmspecid;
        }
        if($ccspecid){
            $str[] = $ccspecid;
        }
        $str = json_encode($str);
        return $str;
    }
    //获取该分类下所有规格属性
    protected  function getpddskuSpecs($cat_id,$spec_cate,$specname){
        $result  = app('pddapi')->request('pdd.goods.spec.get',$this -> accessToken,['cat_id'=>$cat_id]);
//        $result  = $this -> pddarray->request('pdd.goods.spec.get',['access_token' =>$this -> accessToken,'cat_id'=>$cat_id]);
        $result = $result['goods_spec_get_response']['goods_spec_list'];
        $specid = '';
        foreach ($result as $item) {
            if($item['parent_spec_name'] == $spec_cate){
                $specid = $item['parent_spec_id'] ;
            }
        }
        $spec_ids =  $this -> getpddskuSpecsId($specid,$specname);
        return $spec_ids;
    }

    /*  根据pdd.goods.spec.id.get生成的规格属性id
     * $parent_spec_id  拼多多标准规格ID
     * $spec_name 商家编辑的规格值
     * */
    protected  function getpddskuSpecsId($specid,$spec_name){
        $result  = app('pddapi')->request('pdd.goods.spec.id.get',$this -> accessToken,['parent_spec_id'=>$specid,'spec_name'=>$spec_name]);
//        $result  = $this -> pddarray->request('pdd.goods.spec.id.get',['access_token' =>$this -> accessToken,'parent_spec_id'=>$specid,'spec_name'=>$spec_name]);
        return $result['goods_spec_id_get_response']['spec_id'];
    }



    //获取商品信息
    public function goodsdetlits(){
        $result  = app('pddapi')->request('pdd.goods.detail.get');
//        $result  = $this -> pddarray ->request('pdd.goods.detail.get',['goods_id'=>132500610412]);
    }

    //获取运费模板
    public function getTemplates(){
        $result  = app('pddapi')->request('pdd.goods.logistics.template.get',$this -> accessToken);
//        $result  = $this -> pddarray ->request('pdd.goods.logistics.template.get',['access_token' =>$this -> accessToken]);
        $templats = $result['goods_logistics_template_get_response']['logistics_template_list'];

        if($templats == null){
            return $this -> error($result['error_response']['error_code'],$result['error_response']['error_msg']) ;
        }
        $arr = [];
        foreach ($templats as $key => $val){
            $arr[$key]['template_name'] = $val['template_name'];//运费模板名称
            $arr[$key]['template_id'] = $val['template_id'];//	模板id
        }
        return $this -> success('200','获取运费模板成功',$arr);
    }

    //获取商品类目id
    protected  function getcat_id($cname){
        $where = " level > 2";
        $catids = Db::name('pdd_goods_cat') -> where($where) -> where($cname) -> select();
//        dump(Db::name('pdd_goods_cat') -> getLastSql());die;
        $catids = array_sort($catids,'level','desc');
        $catids = array_slice($catids,0,1);
        $catid = $catids[0]['cat_id'];
        return $catid;
    }

    //获取原产地
    protected  function selectCountry(){
        $result  = app('pddapi')->request('pdd.goods.country.get',$this -> accessToken);
//        $result  = $this -> pddarray->request('pdd.goods.country.get',['access_token' =>$this -> accessToken]);
        $result = $result['goods_country_get_response']['country_list'];
        return $result;
    }

    //获取商品属性
    protected function getAttrcats($cat_id,$data){
        $result  = app('pddapi')->request('pdd.goods.cat.template.get',$this -> accessToken,['cat_id'=>$cat_id]);
//        $result  = $this -> pddarray->request('pdd.goods.cat.template.get',['access_token' =>$this -> accessToken,'cat_id'=>$cat_id]);
        $res = $result['open_api_response']['properties'];
        $arr = [];
        foreach ($res as $key => $val){
            foreach ($data as $k => $v){
                if($val['name_alias'] == $v['name']){
                    $arr[$key]['name'] = $val['name_alias'];
                    $arr[$key]['ref_pid'] = $val['ref_pid'];
                    $arr[$key]['spec_id'] = $res['open_api_response']['id'];
                    foreach ($val['values'] as $k1 => $v1){
                        if($v1['value']== $v['value']){
                            $arr[$key]['vvalue'] = $v1['value'];
                            $arr[$key]['vid'] = $v1['vid'];
                        }
                    }
                }
            }
        }
        $arr = array_merge($arr);
        $goods_properties = [];
        foreach ($arr as $key => $val){
            $goods_properties[$key]['group_id'] = '';//组id
            $goods_properties[$key]['img_url'] = '';//图片url
            $goods_properties[$key]['note'] = '';//备注
            $goods_properties[$key]['parent_spec_id'] = '';//父属性id
            $goods_properties[$key]['ref_pid'] = $val['ref_pid'];//	引用属性id
            $goods_properties[$key]['spec_id'] = $val['spec_id'];
            $goods_properties[$key]['template_pid'] = '';
            $goods_properties[$key]['value'] = $val['vvalue'];//属性值
            $goods_properties[$key]['value_unit'] = '';//属性单位
            $goods_properties[$key]['vid'] = $val['vid'];//属性值id
        }
//        dump($goods_properties);die;
        return $goods_properties;
    }



    //商品sku计量单位枚举
    public function getskumeasurement(){
        $result  = app('pddapi')->request('pdd.gooods.sku.measurement.list',$this -> accessToken);
//        $result  = $this -> pddarray->request('pdd.gooods.sku.measurement.list',['access_token' =>$this -> accessToken]);
        $result = $result['gooods_sku_measurement_list_response'];
        return $result;
    }

    public function source_type($type){
        $type_id = '';
        switch ($type){
            case 'taobao':
            case 'tmall' :
                $type_id = 0;
                break;
            case 'jd':
                $type_id = 1;
                break;
            case '1688':
                $type_id = 2;
                break;
            case 'wph':
                $type_id = 3;
                break;
            case 'sn':
                $type_id = 4;
                break;
            case 'ymx':
                $type_id = 5;
                break;
            case 'wy':
                $type_id = 6;
                break;
            case 'wd':
                $type_id = 8;
                break;
            case 'wsy':
                $type_id = 9;
                break;
            case 'mgj':
                $type_id = 10;
                break;
        }

//        外部平台枚举值， 0-淘宝/天猫 ，1-京东，2-1688，
//3-唯品会，4-苏宁，5-亚马逊，6-网易，8-微店，
//9-网商园，10-蘑菇街，11-vvic搜款网，12-搜鞋网，
//13-一起做网店17zwd，14-杭州女装网，15-折800，
//16-当当，17-青创网，18-开山网，19-新款网, 
//20-文轩网，21-博库网，22-四季星座网, 23-童商网，
//24-淘羊网, 25-成都购商云汇网

    }


    public function authkkk(){
        $pinDuoDuoGoodsData = $this -> pinDuoDuo ->request('pdd.goods.list.get',
            ['page' => $this->page, 'page_size' => $this->page_size], ‘用户的access_token’);
        //无需授权
        /** @var string 获取购买应用订单列表 */
//       const API_PDD_VAS_ORDER_SEARCH = 'pdd.vas.order.search';
//       //需授权
//       /** @var string 获取商品列表 */
//       const API_PDD_GOODS_LIST_GET = 'pdd.goods.list.get';
//       /** @var string 获取商品列表 */
//       const API_PDD_GOODS_DETAIL_GET = 'pdd.goods.detail.get';
//       /** @var string 修改商品信息 */
//       const API_PDD_GOODS_INFORMATION_UPDATE = 'pdd.goods.information.update';
//       /** @var string 上传图片 */
//       const API_PDD_GOODS_IMAGE_UPLOAD = 'pdd.goods.image.upload';
//       /** @var string 商品编辑结果查询 */
//       const API_PDD_GOODS_COMMIT_DETAIL_GET = 'pdd.goods.commit.detail.get';
//       /** @var string 获取店铺信息 */
//       const API_PDD_MALL_INFO_GET = 'pdd.mall.info.get';
    }
}
