<?php
//    / **
//    *由PhpStorm创建。
//    *用户：管理员
//    *日期：2020/8/22
//    *时间：12:48
//    * /
namespace app\api\controller;
use DsfApi\PddApi;
use think\facade\Db;
use app\Request;
//use think\Request;
use think\facade\Session;
use think\facade\Cache;
use fast\Image;
use fast\Redis;
use DsfApi\TaoBao;
class Pnduoduo extends Api {
//    protected static $client_id = "919269592dd24bf8959bd07f4e0a569b";// 你的client_id
//    protected static $client_secret = "9d92e889253e0636da0be1de6e15761505c73428"; // 你的client_secret
//    protected static $redirect_uri ="http://www.sxtyyd.com/api/pnduoduo/login";//回调地址
//    protected static $client_id6 = "ec62d493c7f2471cb24ada94ab4d081a";// 企业ERP   bae07a6ea8b25bd739ae1e1b0fba61c0cbcd56b3
//    protected static $client_secret6 = "bae07a6ea8b25bd739ae1e1b0fba61c0cbcd56b3";// 企业ERP   你的client_secret
//
//    protected static $client_id2 =  "e4f6f46de638469abb59bafc6ce5ca28";//促销
//    protected static $client_secret2 =  "aa110ee70f611e8a296e303d0af005212ef37708";//促销
//
//    protected static $client_id3 =  "08a18af2cbaf4439aef73f869e6a99d9";//商品优化
//    protected static $client_secret3 = "485883fa6adb657dcb4c439c14e6a0d9a3e3432b";//商品优化

//    protected static $loginurl = 'http://open-api.pinduoduo.com/oauth/token';
//    protected static $apiurl = "https://gw-api.pinduoduo.com/api/router";
//    protected static $redirect_uri ="http://39.96.83.39:777/api/pnduoduo/login";//回调地址

    protected  $accessToken;
    protected  $pddarray;
    public  function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $pddauth = Db::name('business_application_platform') -> where('name','pdd')  -> field('appkey,appsecret,redirect_uri') -> find();
        $config = array(
            'client_id' =>$pddauth['appkey'], //client_id
            'client_secret' => $pddauth['appsecret'], //client_secret
            'backurl' => $pddauth['redirect_uri'], //回调地址
            'data_type' => 'json', // 返回数据格式
            'pdd_token_file' => __DIR__ . '/pdd_token.txt', // token存储文件地址
        );
        $this -> pddarray = new PddApi($config);
//        epre($this -> pddarray);exit;
        $owner_name = input('owner_name');
         if(empty($owner_name)){
             exit(json_encode($this -> error('401','店铺账号不能为空!'))) ;
         }

        $res = Db::name('shop_open_user')
            -> field('mall_name,access_token,refresh_token,endtime,owner_name,owner_id,is_token')
            -> where(['shop_type'=>'pdd','owner_name'=>$owner_name])
            -> find();
//        if($res['is_token'] != 1){
//            exit(json_encode($this -> error('403','此店铺没有授权!'))) ;
//        }

//        epre(date("Y-m-d H:i:s",$res['endtime']));exit;
//        if(time() - $res['endtime'] > 2*60*60){
//            exit(json_encode($this -> error('403','此店铺授权过期，请重新授权!'))) ;
//        }

        Db::name('shop_open_user')
            -> where(['shop_type'=>'pdd','owner_name'=>$owner_name])
            -> update(['endtime'=>time()]);
         $this -> accessToken = $res['access_token'];
//        $this -> accessToken = '942b856f019c4e869810d68af96bd17c4a7f39f2';
    }

    //获取店铺信息
    public function getShopInfo(){
        $result  = $this -> pddarray -> request('pdd.mall.info.get');
        return $result;
    }

    //商品列表
    public function pddgoodlist(){
       $data =  unserialize(Redis::get($this->uid.'taobao'));
       return $this->success('200','获取成功',$data);
    }

    //导入拼多多图片信息
    public function pdduploadinfo(Request $request){
        $goodsid = $request->post('goodsids');
        // return $goodsid;
        if(empty($goodsid)){
            return $this -> error('401','商品ID不能为空!');
        }
        $res = TaoBao::goodsinfo($goodsid);
        Cache::set($goodsid.'taobao',$res);
//        $res = Cache::get($goodsid.'taobao');
        //  dump($res);die;
        //商品主图
        // Redis::DEL($goodsid. '_product_ztimg');
        $ztimg = Redis::get($goodsid. '_product_ztimg');
        $ztimgurl = '';
        if (!$ztimg) {
             $str = substr($res['pic_url'],-3);
             if($str == 'jpg'){
                  $ztimgurl = $this -> imgupload($res['pic_url'],1,700,700);
             }
            if($ztimgurl == ''){
                return false;
            }
            Redis::set($goodsid . '_product_ztimg', serialize($ztimgurl), 604800);
        }
        $proImg = Redis::get($goodsid . '_product_images_url');
        $pddlunbo = [];//轮播图
        if (!$proImg) {
            $images = array_column($res['item_imgs'], 'url');
            foreach ($images as $v){
                $str = substr($v,-3);
                if($str == 'jpg'){
                    $pddlunbo[] = $this -> imgupload($v,1,700,700);
                }
            }
            Redis::set($goodsid . '_product_images_url', serialize($pddlunbo), 604800);
        }
        $descImg = Redis::get($goodsid . '_product_descImg');
        $desc_img = []; //详情图
        if(!$descImg){
            foreach ($res['desc_img'] as $v){
                $desc_img[] = $this -> imgupload($v,1,700,700);
            }
            Redis::set($goodsid . '_product_descImg', serialize($desc_img), 604800);
        }

        // $data['images_url'] = unserialize(Redis::get($goodsid . '_product_images_url'));
        // $data['desc_img'] = unserialize(Redis::get($goodsid . '_product_descImg'));
        $data['goodsid'] = $goodsid;
        $data['pic_url'] = unserialize(Redis::get($goodsid . '_product_ztimg'));
        return $this->success('200','获取成功', $data);
    }

    //导入上传
    public function pdddaoru(Request $request){
        $goodsid = $request->post('goodsids');
        // return $goodsid;

        if(empty($goodsid)){
            return $this -> error('401','商品ID不能为空!');
        }
        $resinfo = Redis::get($goodsid.'_info');
        if(!$resinfo){
            $res = Cache::get($goodsid.'taobao');
            if(count($res['prop_imgs']) >=20){
                $prop_imgs=array_slice($res['prop_imgs'],0,20);//截取数组
            }else{
                $prop_imgs=$res['prop_imgs'];//截取数组
            }
            if(count($res['prop_imgs']) >=20){
                $skus_list=array_slice($res['skus_list'],0,20);//截取数组
            }else{
                $skus_list=$res['skus_list'];
            }
            $rescate = TaoBao::goodcate($goodsid);
            $cateId = $this -> getcat_id($rescate['root_cat_name'],$rescate['cat_name']);
//            echo $catid;die;
            //查询类目
//            $cate = Db::name('pdd_goods_cat') -> where('cat_name',$rescate['cat_name']) -> select();
            //获取最相近的类目
//            $cateId = $this -> closest_word($rescate['cat_name'], $cate);

            //商品sku列表
            $sku_list = json_encode($this -> skus_list($cateId,$skus_list,$prop_imgs));
            //商品属性
            $goods_properties = json_encode($this -> getAttrcats($cateId,$res['props'],$res['pic_url']));
            $title = $res['title'];
            $desc_short = $res['desc_short'];//商品简介
            $market_price = $res['orginal_price'] * 100 * 2;
//        //商品外部编码
            $out_goods_id = "WPK-T-".$res['goodsid'];
            $carousel_video = json_encode([]);

            $data['cat_id'] = $cateId;
            $data['sku_list'] = $sku_list;
            $data['goods_properties'] = $goods_properties;
            $data['title'] = $title;
            $data['desc_short'] = $desc_short;
            $data['market_price'] = $market_price;
            $data['out_goods_id'] = $out_goods_id;
            $data['carousel_video'] = $carousel_video;
            Redis::set($goodsid.'_info',serialize($data),604800);
        }
        $sudata['goodsid'] = $goodsid;
        return $this->success('200','导入成功', $sudata);
    }


    //开始上传   //商品添加或发布
    public function pddgoodsadd(Request $request){
        $template_id = $request->post('template_id');
        $goods_type = $request->post('goods_type') ?? 1; //1-国内普通商品，2-进口
        $unit_price = $request->post('unit_price') ?? 0;//单价
        $spell_unit_price = $request->post('spell_unit_price') ?? 0;//拼单价
        $goodsid = $request->post('goodsids');
        if(empty($template_id)){
            return $this -> error('401','运费模板不能为空!');
        }
        if(empty($goodsid)){
            return $this -> error('401','商品ID不能为空!');
        }
        $pddsku = unserialize(Redis::get($goodsid.'_info'));
//        dump(unserialize(Redis::get($goodsid.'_info')));die;
        $pdd_data = [
            'access_token' => $this -> accessToken,
            'bad_fruit_claim'=>'',
            'buy_limit'=>'',//限购次数   非必填
            'carousel_video' => $pddsku['carousel_video'],
            'carousel_video_url'=>'',
            'cat_id'=> $pddsku['cat_id'], //叶子类目ID
            'cost_template_id' => $template_id, //物流运费模板ID，可使用pdd.logistics.template.get获取
            'country_id' => 0,//国家ID，country_id可以通过pdd.goods.country.get获取
            'customer_num' => '',//团购人数    非必填
            'customs' => '',//非必填
            'delivery_one_day' => 0,//	是否当日发货,0 否，1 是  非必填
            'carousel_gallery'=> json_encode(unserialize(Redis::get($goodsid.'_product_images_url'))), //商品轮播图
            'detail_gallery'=> json_encode(unserialize(Redis::get($goodsid.'_product_descImg'))),//商品详情图
            'elec_goods_attributes'=>'',
            'goods_name'=> $pddsku['title'] ,//	商品标题
            'goods_desc' => $pddsku['desc_short'],//商品描述
            'goods_properties'=>$pddsku['goods_properties'],//	商品属性列表  非必填
            'goods_trade_attr' => '',//日历商品交易相关信息   非必填
            'goods_travel_attr'=> '',//商品出行信息  非必填
            'goods_type' => $goods_type,//1-国内普通商品，2-进口
            'image_url'=> unserialize(Redis::get($goodsid.'_product_ztimg')),//	商品主图
            'invoice_status' => 0,//是否支持开票（测试中）
            'is_customs' => 'false',//是否需要上报海关，false-无需上报海关，true-需上报海关  非必填
            'is_folt' => 'true',//是否支持假一赔十，false-不支持，true-支持
            'is_pre_sale' => 'false',//是否预售,true-预售商品，false-非预售商品
            'is_refundable' => 'true',//是否7天无理由退换货，true-支持，false-不支持
            'second_hand' => 'false',//是否二手商品，true -二手商品 ，false-全新商品
            'lack_of_weight_claim'=>0 ,//缺重包退  非必填
            'mai_jia_zi_ti' => '',
            'market_price' => $pddsku['market_price'],//市场价格，单位为分
            'order_limit' => 999999,//单次限量   非必填
            'origin_country_id' => '',//原产地id  非必填
            'out_goods_id' => $pddsku['out_goods_id'],//商品编码
            'oversea_goods'=>'', //非必填
            'oversea_type' => 0,//非必填
            'pre_sale_time' => 0,//预售时间，is_pre_sale为true时必传   非必填
            'quan_guo_lian_bao' => 0,//0：不支持全国联保；1：支持全国联保
            'shang_men_an_zhuang' => '',//上门安装模版id  非必填
            'shipment_limit_second' => 48*3600,
            'size_spec_id' => '',//尺码表id  非必填
            'sku_list' => $pddsku['sku_list'],
            'sku_type' => 0,//	库存方式（0：普通型，1：日历型）
            'song_huo_an_zhuang' => '',//送货入户并安装模版id  非必填
            'song_huo_ru_hu' => '',//送货入户模版id  非必填
            'tiny_name' => '',//短标题，示例：新包装   非必填
            'warehouse' => '',//非必填
            'warm_tips' => '',//买家自提模版id
            'zhi_huan_bu_xiu' => 0,//只换不修的天数，目前只支持0和365  非必填
        ];
        $result  = $this -> pddarray ->request('pdd.goods.add',$pdd_data);
        if(!empty($result['error_response'])){
            $data['msg'] =  $result['error_response']['error_msg'];
        }else{
            $data['msg'] = "上传成功";
        }
        $data['goodsid'] = $goodsid;
        return $this->success('200','导入成功',$data);

    }



    protected function addsave($cost_template_id,$goods_type,$info){
//        $start = time();
        $catid = $this -> getcat_id($info['root_cat_name'],$info['cat_name']);

        $pddlunbo = [];//轮播图
        foreach ($info['item_imgs'] as $v){
            $pddlunbo[] = $this -> imgupload($v,1,700,700);;
        }
        $carousel_gallery = json_encode($pddlunbo);
        $desc_img = []; //详情图
        foreach ($info['desc_img'] as $v){
            $desc_img[] = $this -> imgupload($v,1,700,700);
        }
        $detail_gallery = json_encode($desc_img);
//        $detail_gallery = json_encode($this -> imgupload1($info['desc_img']));
//        $carousel_gallery = json_encode($this -> imgupload1($info['item_imgs']));
//        epre($carousel_gallery);
//        $end = time();
//        $counttime = $end - $start;
//        echo "catid获取总耗时".$counttime;die;


        //商品sku列表
        $sku_list = json_encode($this -> skus_list($catid,$info['skus_list'],$info['prop_imgs']));
        //商品属性
        $goods_properties = json_encode($this -> getAttrcats($catid,$info['props']));
        $title = $info['title'];
        $desc_short = $info['desc_short'];//商品简介
        $market_price = $info['orginal_price'] * 100 * 2;
//        //商品外部编码
        $out_goods_id = "WPK-T-".$info['goodsid'];
        $pic_url = $this -> imgupload($info['pic_url'],1,750,352);
        $carousel_video = json_encode([]);
        $this -> pddgoodsave($catid,$carousel_video,$cost_template_id,$carousel_gallery,$detail_gallery,$title,$goods_properties,$market_price,
            $sku_list,$goods_type,$out_goods_id,$pic_url,$desc_short);
    }

    /*上传图片
    * $type 类型 1压缩尺寸 0 不压缩
    */
    public function imgupload($images,$type="",$iwidth="",$iheight=""){
        if(empty($images)){
            return false;
        }
        $imageurl = Image::imgtobase64("http:".$images,$type,$iwidth,$iheight);
        $result  = $this -> pddarray->request('pdd.goods.image.upload',[ 'access_token' =>$this -> accessToken,'image'=>$imageurl]);
        $imgurl = $result['goods_image_upload_response']['image_url'];
        return  $imgurl;
    }


    /*  获取商品的sku
         *  $pdd_catid 商品类目id
         *   $resskulist  sku 数据
         *   $thumb_urls 缩略图
         * */
    protected function skus_list($pdd_catid,$resskulist,$thumb_urls){
        $oversea_sku = [
            "measurement_code" => '001',//计量单位编码，从接口pdd.gooods.sku.measurement.list获取code
            "specifications" => "2",//规格
            "taxation" => 100,//税费
        ];
        $thumburl = [];
        foreach ($thumb_urls as $k => $v) {
            $thumburl[$v['properties']] = $v['url'];
        }
        $sku_list = [];
        foreach ($resskulist as $key => $val){
            $propImg = explode(';', $val['properties_name']);
            $ysstr = '';
            $a = '';
            $b = '';
            $cmstr = '';
            foreach ($propImg as $v) {
                if ( strpos($v, '颜色')) {
                    $a = strpos($v, '颜色');
                    $ysstr = $v;
                }
                if(strpos($v, '尺码')){
                    $b = strpos($v, '尺码');
                    $cmstr = $v;
                }
            }
            $ye = substr($ysstr, $a, strlen($ysstr));
            $cm = substr($cmstr, $b, strlen($cmstr));
            $propImgNum = substr($ysstr, 0, $a - 1);
            $sku_list[$key]['is_onsale'] = 1;
            $sku_list[$key]['limit_quantity'] = 999;
            $sku_list[$key]['weight'] = 1000;
            $sku_list[$key]['price'] = $val['price'] * 100;
            $sku_list[$key]['multi_price'] = $val['price'] * 100 - 100;
            $sku_list[$key]['thumb_url'] = $this -> imgupload($thumburl[$propImgNum]);
            $sku_list[$key]['out_sku_sn'] = "";//商品sku外部编码
            $spec_id_list = $this ->skupc_list($pdd_catid,$ye,$cm,'','','');
            $sku_list[$key]['spec_id_list'] = $spec_id_list;
            $sku_list[$key]['spec_id_list'] = $this ->skupc_list($pdd_catid,$ye,$cm,'','','');
            $sku_list[$key]['quantity'] = $val['quantity'];
            $sku_list[$key]['oversea_sku'] = $oversea_sku;
            $sku_list[$key]['length'] = '';
        }
        foreach ($sku_list as $key => $val){
            if($val['spec_id_list'] == '[]'){
                unset($sku_list[$key]);
            }
        }
        return $sku_list;
    }
    //商品规格值ID
    protected function skupc_list($cat_id,$ye ="",$cm="",$re='',$rs='',$r1=''){
        $yearr = explode(':',$ye);
        $cmarr = explode(':',$cm);
        $yespecid = $this -> getpddskuSpecs($cat_id,substr($yearr[0],0,6),$yearr[1]);
        $cmspecid = $this -> getpddskuSpecs($cat_id,$cmarr[0],$cmarr[1]);
        $str = [];
        if($yespecid){
            $str[] = $yespecid;
        }
        if($cmspecid){
            $str[] = $cmspecid;
        }
        $str = json_encode($str);
        return $str;
    }
    //获取该分类下所有规格属性
    protected  function getpddskuSpecs($cat_id,$spec_cate,$specname){
        $result  = $this -> pddarray->request('pdd.goods.spec.get',['access_token' =>$this -> accessToken,'cat_id'=>$cat_id]);
        $result = $result['goods_spec_get_response']['goods_spec_list'];
        $specid = '';
        foreach ($result as $item) {
            if($item['parent_spec_name'] == $spec_cate){
                $specid = $item['parent_spec_id'] ;
            }
        }
        $spec_ids =  $this -> getpddskuSpecsId($specid,$specname);
        return $spec_ids;
    }

    /*  根据pdd.goods.spec.id.get生成的规格属性id
     * $parent_spec_id  拼多多标准规格ID
     * $spec_name 商家编辑的规格值
     * */
    protected  function getpddskuSpecsId($specid,$spec_name){
        $result  = $this -> pddarray->request('pdd.goods.spec.id.get',['access_token' =>$this -> accessToken,'parent_spec_id'=>$specid,'spec_name'=>$spec_name]);
        return $result['goods_spec_id_get_response']['spec_id'];
    }

    /* 添加商品数据
     * $catid 类目id
     * $carousel_video //视频
     * $template_id 模板id
     * $carousel_gallery 轮播图
     * $detail_gallery 详情图
     * $title  商品标题
     * $goods_properties  商品属性列表
     * $market_price 市场价格
     * $sku_list
     * $goods_type 1-国内普通商品，2-进口
     * $out_goods_id 商品编码
     * $pic_url 商品主图
     * */
    protected function pddgoodsave($catid,$carousel_video,$template_id,$carousel_gallery,$detail_gallery,$title,$goods_properties,$market_price,
                                   $sku_list,$goods_type,$out_goods_id,$pic_url,$desc_short){
        $pdd_data = [
            'access_token' => $this -> accessToken,
            'bad_fruit_claim'=>'',
            'buy_limit'=>'',//限购次数   非必填
            'carousel_video' => $carousel_video,
            'carousel_video_url'=>'',
            'cat_id'=> $catid, //叶子类目ID
            'cost_template_id' => $template_id, //物流运费模板ID，可使用pdd.logistics.template.get获取
            'country_id' => 0,//国家ID，country_id可以通过pdd.goods.country.get获取
            'customer_num' => '',//团购人数    非必填
            'customs' => '',//非必填
            'delivery_one_day' => 0,//	是否当日发货,0 否，1 是  非必填
            'carousel_gallery'=> $carousel_gallery, //商品轮播图
            'detail_gallery'=> $detail_gallery,//商品详情图
            'elec_goods_attributes'=>'',
            'goods_name'=> $title,//	商品标题
            'goods_desc' => $desc_short,//商品描述
            'goods_properties'=>$goods_properties,//	商品属性列表  非必填
            'goods_trade_attr' => '',//日历商品交易相关信息   非必填
            'goods_travel_attr'=> '',//商品出行信息  非必填
            'goods_type' => $goods_type,//1-国内普通商品，2-进口
            'image_url'=> $pic_url,//	商品主图
            'invoice_status' => 0,//是否支持开票（测试中）
            'is_customs' => 'false',//是否需要上报海关，false-无需上报海关，true-需上报海关  非必填
            'is_folt' => 'true',//是否支持假一赔十，false-不支持，true-支持
            'is_pre_sale' => 'false',//是否预售,true-预售商品，false-非预售商品
            'is_refundable' => 'true',//是否7天无理由退换货，true-支持，false-不支持
            'second_hand' => 'false',//是否二手商品，true -二手商品 ，false-全新商品
            'lack_of_weight_claim'=>0 ,//缺重包退  非必填
            'mai_jia_zi_ti' => '',
            'market_price' => $market_price,//市场价格，单位为分
            'order_limit' => 999999,//单次限量   非必填
            'origin_country_id' => '',//原产地id  非必填
            'out_goods_id' => $out_goods_id,//商品编码
            'oversea_goods'=>'', //非必填
            'oversea_type' => 0,//非必填
            'pre_sale_time' => 0,//预售时间，is_pre_sale为true时必传   非必填
            'quan_guo_lian_bao' => 0,//0：不支持全国联保；1：支持全国联保
            'shang_men_an_zhuang' => '',//上门安装模版id  非必填
            'shipment_limit_second' => 48*3600,
            'size_spec_id' => '',//尺码表id  非必填
            'sku_list' => $sku_list,
            'sku_type' => 0,//	库存方式（0：普通型，1：日历型）
            'song_huo_an_zhuang' => '',//送货入户并安装模版id  非必填
            'song_huo_ru_hu' => '',//送货入户模版id  非必填
            'tiny_name' => '',//短标题，示例：新包装   非必填
            'warehouse' => '',//非必填
            'warm_tips' => '',//买家自提模版id
            'zhi_huan_bu_xiu' => 0,//只换不修的天数，目前只支持0和365  非必填
        ];
        epre($pdd_data);
        $result  = $this -> pddarray ->request('pdd.goods.add',$pdd_data);
        epre($result);
        return $result;
    }


    //获取商品信息
    public function goodsdetlits(){
        $result  = $this -> pddarray ->request('pdd.goods.detail.get',['goods_id'=>132500610412]);
        epre($result);exit;
    }

    //获取运费模板
    public function getTemplates(){
        $result  = $this -> pddarray ->request('pdd.goods.logistics.template.get',['access_token' =>$this -> accessToken]);
        if(!empty($result['error_response'])){
            dump($result['error_response']);die;
            return $this -> error($result['error_response']['error_code'],$result['error_response']['error_msg']) ;
        }else{
            $templats = $result['goods_logistics_template_get_response']['logistics_template_list'];
            $arr = [];
            foreach ($templats as $key => $val){
                $arr[$key]['template_name'] = $val['template_name'];//运费模板名称
                $arr[$key]['template_id'] = $val['template_id'];//	模板id
            }
            return $this -> success('200','获取运费模板成功',$arr);
        }
    }

    //获取商品类目id
    protected  function getcat_id($root_cat_name,$cname){
        $res = Db::name('pdd_goods_cat') -> where('cat_name',$cname) -> select() -> toArray();
        $catid = '';
        if(count($res) == 1){
            $catid = $res[0]['cat_id'];
        }else{
            $rootid = Db::name('pdd_goods_cat') -> where('cat_name',$root_cat_name) -> value('cat_id');
            $ress = Db::name('pdd_goods_cat') -> where('parent_cat_id',$rootid) -> select();
            foreach ($ress as $key => $val){
                $resss = Db::name('pdd_goods_cat') -> where('parent_cat_id',$val['cat_id']) -> select();

                foreach ($resss as $kk => $vv){
                    if($vv['cat_name'] == $cname){
                        $catid =  $vv['cat_id'];
                    }
                }
            }
        }
        return  $catid;

//        $catid = Db::name('pdd_goods_cat') -> where('cat_name',$cname) -> value('cat_id');
        //获取到当前商家可发布类目树
//        $result  = $this -> pddarray ->request('pdd.goods.authorization.cats');
//        if(empty($result['goods_auth_cats_get_response']['goods_cats_list'])){
//            return $result['error_response'];
//        }
    }



    //获取原产地
    protected  function selectCountry(){
        $result  = $this -> pddarray->request('pdd.goods.country.get',['access_token' =>$this -> accessToken]);
        $result = $result['goods_country_get_response']['country_list'];
        return $result;
    }

    //获取商品属性
    protected function getAttrcats($cat_id,$data){
        $result  = $this -> pddarray->request('pdd.goods.cat.template.get',['access_token' =>$this -> accessToken,'cat_id'=>$cat_id]);
        $res = $result['open_api_response']['properties'];
        $arr = [];
        foreach ($res as $key => $val){
            foreach ($data as $k => $v){
                if($val['name_alias'] == $v['name']){
                    $arr[$key]['name'] = $val['name_alias'];
                    $arr[$key]['ref_pid'] = $val['ref_pid'];
                    $arr[$key]['spec_id'] = $res['open_api_response']['id'];
                    foreach ($val['values'] as $k1 => $v1){
                        if($v1['value']== $v['value']){
                            $arr[$key]['vvalue'] = $v1['value'];
                            $arr[$key]['vid'] = $v1['vid'];
                        }
                    }
                }
            }
        }
        $arr = array_merge($arr);
        $goods_properties = [];
        foreach ($arr as $key => $val){
            $goods_properties[$key]['group_id'] = '';//组id
            $goods_properties[$key]['img_url'] = '';//图片url
            $goods_properties[$key]['note'] = '';//备注
            $goods_properties[$key]['parent_spec_id'] = '';//父属性id
            $goods_properties[$key]['ref_pid'] = $val['ref_pid'];//	引用属性id
            $goods_properties[$key]['spec_id'] = $val['spec_id'];
            $goods_properties[$key]['template_pid'] = '';
            $goods_properties[$key]['value'] = $val['vvalue'];//属性值
            $goods_properties[$key]['value_unit'] = '';//属性单位
            $goods_properties[$key]['vid'] = $val['vid'];//属性值id
        }
//        dump($goods_properties);die;
        return $goods_properties;
    }


    //商品sku缩略图
    protected function thump_img($data,$id){
        foreach ($data as $key => $val){
            if($val['properties'] == $id) {
                $thumpurl = $val['url'];
            }
        }
        return $thumpurl;
    }




    //商品sku计量单位枚举
    public function getskumeasurement(){
        $result  = $this -> pddarray->request('pdd.gooods.sku.measurement.list',['access_token' =>$this -> accessToken]);
        $result = $result['gooods_sku_measurement_list_response'];
        return $result;
    }





    /* 获取拼多多类目树
            * $pid  父类id
            */
    protected  function PddcateTree($pid){
        $cate = [];
        $result  = $this -> pddarray->request('pdd.goods.cats.get',['access_token' =>$this -> accessToken,'parent_cat_id'=>$pid]);
//        if(!$result['goods_cats_get_response']['goods_cats_list']){
//            epre($result['error_response']);exit;
//        }
        foreach ($result['goods_cats_get_response']['goods_cats_list'] as $key => $val){
            $cate[$key]['level'] = $val['level'];
            $cate[$key]['cat_id'] = $val['cat_id'];
            $cate[$key]['parent_cat_id'] = $val['parent_cat_id'];
            $cate[$key]['cat_name'] = $val['cat_name'];
        }
        return $cate;
    }



    //获取到当前商家可发布类目树
    public  function pddTree(){
//        $result  = $this -> pddarray->request('pdd.goods.cats.get',['parent_cat_id'=>17428]);//
//        epre($result);exit;

        //判断一级类目是否存在
        $treecate1 = Db::name('pdd_goods_cat') -> where('level',1) -> select();
        if(empty($treecate1)){
            //获取一级类目
            $cate1 = self::PddcateTree(0);
            foreach ($cate1 as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['month'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
        }else{
            $catetreetime2 = Db::name('pdd_goods_cat') -> where('level',1) -> value('end_time');
            if(time() - strtotime($catetreetime2) > 0){
                $cate1 = self::PddcateTree(0);
                foreach ($cate1 as $k1=>$v2){
                    $v2['end_time'] = getday()['month'];
                    Db::name('pdd_goods_cat') -> where('cat_id',$v2['cat_id']) -> update($v2);
                }
            }
//            foreach ($treecate1 as $key => $val){
//                if(time() - strtotime($val['end_time']) > 0){
//
//                }
//            }
        }

        //判断二级分类
        $treecate2 = Db::name('pdd_goods_cat') -> where('level',2)  -> select();
        $cate3 =[];
        if(empty($treecate2)){
            foreach ($treecate1 as $key => $val){
                $cate2[$key] = self::PddcateTree($val['cat_id']);
                $cate3 = array_merge_recursive($cate3,$cate2[$key]);
            }
            foreach ($cate3 as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
        }else{
            //查询二级分类到期更新时间
            $catetreetime2 = Db::name('pdd_goods_cat') -> where('level',2) -> value('end_time');
            if(time() - strtotime($catetreetime2) > 0){
                foreach ($treecate1 as $key => $val){
                    sleep(1);
                    $cate2[$key] = self::PddcateTree($val['cat_id']);
                    $cate3 = array_merge_recursive($cate3,$cate2[$key]);
                }
                foreach ($cate3 as $k1=>$v2){
                    $v2['end_time'] = getday()['week'];
                    Db::name('pdd_goods_cat') -> where('cat_id',$v2['cat_id']) -> update($v2);
                }
            }
        }

        //判断三级分类
        $treecate3 = Db::name('pdd_goods_cat') -> where('level',3) -> select();
        if(empty($treecate3)){
            $cate4 =[];
            $cate5 =[];
            $result = Db::name('pdd_goods_cat') -> where('level',2)
                ->where('id','>',107) -> where('id','<',707) -> select();
            foreach ($result as $key => $val){
                $cate31[$key] = self::PddcateTree($val['cat_id']);
                $cate4 = array_merge_recursive($cate4,$cate31[$key]);
            }
            foreach ($cate4 as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
            $result1 = Db::name('pdd_goods_cat') -> where('level',2)
                ->where('id','>',707) -> where('id','<',1443) -> select();
            foreach ($result1 as $key => $val){
                $cate32[$key] = self::PddcateTree($val['cat_id']);
                $cate5 = array_merge_recursive($cate5,$cate32[$key]);
            }

            foreach ($cate5 as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
        }else{
            //查询三级分类到期更新时间
            $catetreetime3 = Db::name('pdd_goods_cat') -> where('level',3) -> value('end_time');
            if(time() - strtotime($catetreetime3) > 0){
                echo 222222222;exit;
            }
        }
        //判断四级分类
        $treecate4 = Db::name('pdd_goods_cat') -> where('level',4) -> select();
        if(empty($treecate4)){
            $cate61 =[];
            if(empty(Session::get('insertcate41'))){
                $result = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',1443) -> where('id','<',2443) -> select();
                foreach ($result as $key => $val){
                    $result11  = $this -> pddarray->request('pdd.goods.cats.get',['parent_cat_id'=>$val['cat_id']]);
                    $cate41[$key] = $result11['goods_cats_get_response']['goods_cats_list'];
                    $cate61 = array_merge_recursive($cate61,$cate41[$key]);
                }
                Session::set('insertcate41',$cate61);
            }
            foreach (Session::get('insertcate41') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
//            epre(Session::get('insertcate41'));
            $cate62 =[];
            if(empty(Session::get('insertcate42'))){
                $result1 = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',2443) -> where('id','<',3443) -> select();
                foreach ($result1 as $key => $val){
                    $cate42[$key] = self::PddcateTree($val['cat_id']);
                    $cate62 = array_merge_recursive($cate62,$cate42[$key]);
                }
                Session::set('insertcate42',$cate62);
            }
            foreach (Session::get('insertcate42') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }


            $cate63 =[];
            if(empty(Session::get('insertcate43'))){
                $result2 = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',3443) -> where('id','<',4443) -> select();
                foreach ($result2 as $key => $val){
                    $cate43[$key] = self::PddcateTree($val['cat_id']);
                    $cate63 = array_merge_recursive($cate63,$cate43[$key]);
                }
                Session::set('insertcate43',$cate63);
            }
            foreach (Session::get('insertcate43') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }


            $cate64 =[];
            if(empty(Session::get('insertcate44'))){
                $result3 = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',4443) -> where('id','<',5443) -> select();
                foreach ($result3 as $key => $val){
                    $cate44[$key] = self::PddcateTree($val['cat_id']);
                    $cate64 = array_merge_recursive($cate64,$cate44[$key]);
                }
                Session::set('insertcate44',$cate64);
            }
            foreach (Session::get('insertcate44') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
            $cate65 =[];
            if(empty(Session::get('insertcate45'))){
                $result4 = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',5443) -> where('id','<',6443) -> select();

                foreach ($result4 as $key => $val){
                    $cate45[$key] = self::PddcateTree($val['cat_id']);
                    $cate65 = array_merge_recursive($cate65,$cate45[$key]);
                }
                Session::set('insertcate45',$cate65);
            }
            foreach (Session::get('insertcate45') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }

            $cate66 =[];
            if(empty(Session::get('insertcate46'))){
                $result5 = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',6443) -> where('id','<',7443) -> select();
                foreach ($result5 as $key => $val){
                    $result11  = $this -> pddarray->request('pdd.goods.cats.get',['parent_cat_id'=>$val['cat_id']]);
                    $cate46[$key] = $result11['goods_cats_get_response']['goods_cats_list'];
                    $cate66 = array_merge_recursive($cate66,$cate46[$key]);
                }
                Session::set('insertcate46',$cate66);
            }
            foreach (Session::get('insertcate46') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }

            $cate67 =[];
            if(empty(Session::get('insertcate47'))){
                $result6 = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',7443) -> where('id','<',8443) -> select();
                foreach ($result6 as $key => $val){
                    $cate47[$key] = self::PddcateTree($val['cat_id']);
                    $cate67 = array_merge_recursive($cate67,$cate47[$key]);
                }
                Session::set('insertcate47',$cate67);
            }
            foreach (Session::get('insertcate47') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
            $cate68 =[];
            if(empty(Session::get('insertcate48'))){
                $result7 = Db::name('pdd_goods_cat') -> where('level',3)
                    ->where('id','>',8443) -> where('id','<',9345) -> select();
                foreach ($result7 as $key => $val){
                    $cate48[$key] = self::PddcateTree($val['cat_id']);
                    $cate68 = array_merge_recursive($cate68,$cate48[$key]);
                }
                Session::set('insertcate48',$cate68);
            }
            foreach (Session::get('insertcate48') as $key => $val){
                $val['create_time'] = date('Y-m-d H:i:s',time());
                $val['end_time'] = getday()['week'];
                $res = Db::name('pdd_goods_cat') -> where('cat_id',$val['cat_id']) -> find();
                if(empty($res)){
                    Db::name('pdd_goods_cat') -> insert($val);
                }
            }
        }
    }








    /**
     * evaluation_rules表
     * 当店铺初次授权生成初始化期望dsr值
     * @param $ownerId
     * @throws \think\Exception
     */
    public function saveInitDsr($ownerId){
        $db2 = Db::connect('pfpartner2');
        $evaluationRule['owner_id'] = $ownerId;
        $evaluationRule['default_evaluate'] = '1';
        $evaluationRule['remarks_evaluate'] = '1';
        $evaluationRule['dsr_score_describe'] = '5';
        $evaluationRule['dsr_score_logistics'] = '5';
        $evaluationRule['dsr_score_attitude'] = '5';
        $db2->name('evaluation_rules')->insert($evaluationRule);
    }

    /**
     * purchase_record表
     * 当店铺初次授权生成初始化免费试用记录
     * @param $ownerId
     * @param $mallName
     * @throws \think\Exception
     */
    public function saveFreeRecord($ownerId,$mallName){
        $db2 = Db::connect('pfpartner2');
        $initRecord['owner_id'] = $ownerId;
        $initRecord['mall_name'] = $mallName;
        $initRecord['data_date'] = date('Y-m-d');
        $initRecord['product_name'] = '免费试用';
        $initRecord['product_type'] = '2';
        $initRecord['payment_method'] = '2';
        $initRecord['product_details'] = '免费试用';
        $initRecord['start_time'] = date('Y-m-d H:i:s');
        $initRecord['end_time'] = date('Y-m-d H:i:s', strtotime('7 days'));
        $initRecord['day'] = '7';
        $initRecord['original_price'] = '0';
        $initRecord['discount_price'] = '0';
        $initRecord['actual_price'] = '0';
        $db2->name('purchase_record')->insert($initRecord);

    }
}
