<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/8/28
 * Time: 16:08
 */
namespace app\api\controller;
use DsfApi\PddApi;
use think\App;
use think\facade\Db;
use think\facade\Session;
use app\Request;
class Shopauth extends Api {
    protected $pddauth;
    protected $noNeedToken = ['pddauthlogin'];
    public function initialize(){
//        dump($this -> uid);die;
        parent::initialize(); // TODO: Change the autogenerated stub
        $this -> pddauth = Db::name('business_application_platform') -> where('name','pdd')  -> field('appkey,appsecret,redirect_uri') -> find();
    }
    //拼多多授权登录
    public function pddauthlogin(Request $request){
        $userid = $this -> uid ?? 1;//用户ID
        // 接口配置
        $config = array(
            'client_id' => $this -> pddauth['appkey'], //client_id
            'client_secret' => $this -> pddauth['appsecret'], //client_secret
            'backurl' => $this -> pddauth['redirect_uri'], //回调地址
            'data_type' => 'json', // 返回数据格式
            'pdd_token_file' => __DIR__ . '/pdd_token.txt', // token存储文件地址
        );
        $pddarray = new PddApi($config);
//        echo '<a href="' . $this -> getHref($this -> pddauth['appkey'],$this -> pddauth['redirect_uri'],'') . '">商家授权</a><br />';
        $token = $pddarray ->getAccessToken();

        $resArr = json_decode($token,true);
        if(empty($resArr)){
            exit(json_encode( $this -> error('401','access_token过期，请重新登录!')));
        }else{
            //获取店铺信息
            // 调用这个方法，将会保存token到你设置的文件。
//           $this -> pddarray ->saveToken($token);
//            $accessToken = $pddarray  -> createAuthorization($resArr['access_token']);
            $shopInfo  = $pddarray -> request('pdd.mall.info.get',['access_token' =>$resArr['access_token']]);
            if($shopInfo['error_response']['sub_code'] == "70036"){
                return '调用次数被限制';
            }
            if (empty($shopInfo["mall_info_get_response"])){
                header($this -> pddauth['redirect_uri']);
//                return $this-> redirect($this -> pddauth['redirect_uri']);
            }
            $res = $this -> getshopadd($userid,$resArr,$shopInfo);
            if($res == 1){
                return redirect('http://www.sxtyyd.com/index/pddcallback?pddtoken='.md5($resArr['access_token']));
            }
        }
    }


    //添加店铺
    public function getshopadd($userid,$resArr,$shopInfo){
        //判断该店铺是否授权过
        $user = Db::name("shop_open_user")->where(['owner_id'=>$resArr['owner_id'],'owner_name'=>$resArr['owner_name']])->find();
        //$this -> shopopenuser -> selectone(['owner_id'=>$resArr['owner_id'],'owner_name'=>$resArr['owner_name']]);
        /***店铺信息S*************************************/
        $userInfo['logo'] = $shopInfo["mall_info_get_response"]['logo'];
        $userInfo['mall_name'] = $shopInfo["mall_info_get_response"]['mall_name'];
        $userInfo['mall_desc'] = $shopInfo["mall_info_get_response"]['mall_desc'];
        /***店铺信息E*************************************/
        $userInfo['shop_type'] = 'pdd';//属于哪个平台
        $userInfo['owner_id'] = $resArr['owner_id'];
        $userInfo['owner_name'] = $resArr['owner_name'];
        $userInfo['login_time'] = date('Y-m-d H:i:s');
        $userInfo['access_token'] = $resArr['access_token'];
        $userInfo['expires_in'] = $resArr['expires_in'];
        $userInfo['refresh_token'] = $resArr['refresh_token'];
        $userInfo['scope'] = json_encode($resArr['scope']);
        $userInfo['is_token'] = 1;//授权状态
        $userInfo['is_cookie'] = '0';
        $userInfo['endtime'] = time();
        $userInfo['uid'] = $userid;
        /***记录登录日志S*************************************/
        $loginLog['shop_type'] = 'pdd';
        $loginLog['uid'] = $userid;
        $loginLog['owner_id'] = $resArr['owner_id'];
        $loginLog['mall_name'] = $shopInfo["mall_info_get_response"]['mall_name'];
        $loginLog['open_info'] = json_encode($resArr);
        Db::name("shop_login_log")->insert($loginLog);
        /***记录登录日志E*************************************/
        ///店铺之前未授权信息初始化S//////////////////////////////////////////////////
        if(empty($user)){
            $userInfo['is_lock'] = '0';
            $userInfo['state'] = '0';
            $userInfo['login_num'] = 1;
            $userInfo['lock_time'] = date('Y-m-d H:i:s', strtotime('7 days'));
            $userInfo['cookie_expires_time'] = date('Y-m-d H:i:s');//cookie被封时间
            ///最后生成增量任务时间S////////////////////////////////////////////////////
            $addRes = Db::name("shop_open_user") -> insert($userInfo);
            //用户信息存入session
            Session::set('shop_user',$userInfo);
            ///新增请求执行任务等创建E//////////////////////////////////////////////////////
            if ($addRes){
                // $this -> pddshopshtml($shopInfo["mall_info_get_response"],$userid,$resArr['owner_id']);
                return 1;
            }else{
                return 0;
            }
            ///店铺之前未授权信息初始化E//////////////////////////////////////////////////
        }else{
            $userInfo['login_num'] = $user['login_num']+1;
            $updateRes = Db::name("shop_open_user")->where(['shop_type'=>'pdd','owner_id'=>$resArr['owner_id']])->update($userInfo);
            if ($updateRes){
                $updatedUser = Db::name("shop_open_user")->where(['shop_type'=>'pdd','owner_id'=>$resArr['owner_id']])->find();
                //用户信息存入session
//                epre($updatedUser);exit;
                Session::set('shop_user',$updatedUser);
                // $this -> pddshopshtml($shopInfo["mall_info_get_response"],$userid,$resArr['owner_id']);
                return 1;
//                return $this->redirect('index/Home/index',['code' => $state]);
            }else{
                return 0;
            }
        }
    }


    /* 获取拼多多类目树
      * $pid  父类id
      */
    protected function pddcate($pid){

    }

    //    //生成登录链接
    public function getHref($client_id,$redirect_uri,$type = ''){
        $userid = $this -> uid ?? 1;
        $query = 'response_type=code&client_id=' .$client_id. '&redirect_uri=' . urlencode( $redirect_uri) . '&state='.$userid;
        if ($type == 'ddk') {
            return 'https://jinbao.pinduoduo.com/open.html?' . $query; // 拼客客
        }
        if (is_mobile() != true) {
            $url = 'https://mms.pinduoduo.com/open.html?' . $query; // pc端
        } else {
            $url = 'https://mai.pinduoduo.com/h5-login.html?' . $query . '&view=h5'; // 手机端
        }
        return $url;
    }

}
